### ISSUE TITLE
Upgrade to API version v2 and more output

### ISSUE THREAD

**Issue by Chrico** [InstaWP/wordpress-testing-automation#19]
There is already an API in version 2 available which has some more output (like username, password). Is it possible to update this action to support the version 2 of the API?

---

## Links

- "create site" - https://docs.instawp.com/en/article/create-a-site-via-api-fq00b5/

**Comment by vikasprogrammer** [comment]
Good point, releasing soon. sorry about the delay.

**Comment by vikasprogrammer** [comment]
We have updated the API to use v2 but I can see that username, password are already available in v1 too. 

Use the main branch for latest version, I will do a release after your testing and feedback.

**Comment by Chrico** [comment]
As far as I can see from this documentation https://docs.instawp.com/en/article/create-a-site-via-api-fq00b5/  the response data is:

```json
{
    "status": true,
    "message": "Site installation work is completed, Your website is ready!",
    "data": {
        "message": "Site installation work is completed, Your website is ready!",
        "is_pool": true,
        "status": 1,
        "wp_url": "https://xyzsitename.instawp.xyz",
        "wp_username": "zuvalebuca7835",
        "wp_password": "iUnzmX2l1WRk3uMQA0NS",
        "id": 1333819,
        "s_hash": "$2y$10$xviWFKNaIREgtkLWQw6Jnurgk8ePIT9AGyWvS8DoFscqQP4BfqAmu",
        "token": null,
        "remaining_site_minutes": 1439,
        "install_content_task_id": false,
        "dispatch_migrate_v3": false
    }
}
```

But according due the code only following data is used:

```ts
const results_url = results.data.wp_url;
const results_site_id = results.data.id;
const results_login = `https://${domain}/wordpress-auto-login?site=${results.data.s_hash}`;
```
